// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, Endpoint, HandlerFunction } from './types';

export { Metadata, Endpoint, HandlerFunction };

import list_account_charts_number_3 from './number-3/list-account-charts-number-3';
import list_print_templates_number_3 from './number-3/list-print-templates-number-3';
import retrieve_company_information_number_3 from './number-3/retrieve-company-information-number-3';
import retrieve_eu_vat_limit_regulation_number_3 from './number-3/retrieve-eu-vat-limit-regulation-number-3';
import retrieve_sie_file_number_3 from './number-3/retrieve-sie-file-number-3';
import retrieve_user_information_number_3 from './number-3/retrieve-user-information-number-3';
import retrieve_vacation_debt_basis_number_3 from './number-3/retrieve-vacation-debt-basis-number-3';
import create_number_3_absencetransactions from './number-3/absencetransactions/create-number-3-absencetransactions';
import retrieve_number_3_absencetransactions from './number-3/absencetransactions/retrieve-number-3-absencetransactions';
import update_number_3_absencetransactions from './number-3/absencetransactions/update-number-3-absencetransactions';
import list_number_3_absencetransactions from './number-3/absencetransactions/list-number-3-absencetransactions';
import delete_number_3_absencetransactions from './number-3/absencetransactions/delete-number-3-absencetransactions';
import retrieve_by_date_and_code_number_3_absencetransactions from './number-3/absencetransactions/retrieve-by-date-and-code-number-3-absencetransactions';
import create_number_3_accounts from './number-3/accounts/create-number-3-accounts';
import retrieve_number_3_accounts from './number-3/accounts/retrieve-number-3-accounts';
import update_number_3_accounts from './number-3/accounts/update-number-3-accounts';
import list_number_3_accounts from './number-3/accounts/list-number-3-accounts';
import delete_number_3_accounts from './number-3/accounts/delete-number-3-accounts';
import retrieve_number_3_archive from './number-3/archive/retrieve-number-3-archive';
import delete_file_number_3_archive from './number-3/archive/delete-file-number-3-archive';
import remove_files_number_3_archive from './number-3/archive/remove-files-number-3-archive';
import retrieve_file_number_3_archive from './number-3/archive/retrieve-file-number-3-archive';
import upload_file_number_3_archive from './number-3/archive/upload-file-number-3-archive';
import create_number_3_articlefileconnections from './number-3/articlefileconnections/create-number-3-articlefileconnections';
import retrieve_number_3_articlefileconnections from './number-3/articlefileconnections/retrieve-number-3-articlefileconnections';
import list_number_3_articlefileconnections from './number-3/articlefileconnections/list-number-3-articlefileconnections';
import remove_number_3_articlefileconnections from './number-3/articlefileconnections/remove-number-3-articlefileconnections';
import create_number_3_articles from './number-3/articles/create-number-3-articles';
import retrieve_number_3_articles from './number-3/articles/retrieve-number-3-articles';
import update_number_3_articles from './number-3/articles/update-number-3-articles';
import list_number_3_articles from './number-3/articles/list-number-3-articles';
import delete_number_3_articles from './number-3/articles/delete-number-3-articles';
import create_number_3_articleurlconnections from './number-3/articleurlconnections/create-number-3-articleurlconnections';
import retrieve_number_3_articleurlconnections from './number-3/articleurlconnections/retrieve-number-3-articleurlconnections';
import update_number_3_articleurlconnections from './number-3/articleurlconnections/update-number-3-articleurlconnections';
import list_number_3_articleurlconnections from './number-3/articleurlconnections/list-number-3-articleurlconnections';
import remove_number_3_articleurlconnections from './number-3/articleurlconnections/remove-number-3-articleurlconnections';
import create_number_3_assetfileconnections from './number-3/assetfileconnections/create-number-3-assetfileconnections';
import list_number_3_assetfileconnections from './number-3/assetfileconnections/list-number-3-assetfileconnections';
import delete_number_3_assetfileconnections from './number-3/assetfileconnections/delete-number-3-assetfileconnections';
import create_number_3_assets from './number-3/assets/create-number-3-assets';
import retrieve_number_3_assets from './number-3/assets/retrieve-number-3-assets';
import update_number_3_assets from './number-3/assets/update-number-3-assets';
import list_number_3_assets from './number-3/assets/list-number-3-assets';
import delete_number_3_assets from './number-3/assets/delete-number-3-assets';
import change_ob_number_3_assets from './number-3/assets/change-ob-number-3-assets';
import depreciate_number_3_assets from './number-3/assets/depreciate-number-3-assets';
import list_depreciations_number_3_assets from './number-3/assets/list-depreciations-number-3-assets';
import scrap_number_3_assets from './number-3/assets/scrap-number-3-assets';
import sell_number_3_assets from './number-3/assets/sell-number-3-assets';
import write_down_number_3_assets from './number-3/assets/write-down-number-3-assets';
import write_up_number_3_assets from './number-3/assets/write-up-number-3-assets';
import create_assets_number_3_types from './number-3/assets/types/create-assets-number-3-types';
import retrieve_assets_number_3_types from './number-3/assets/types/retrieve-assets-number-3-types';
import update_assets_number_3_types from './number-3/assets/types/update-assets-number-3-types';
import list_assets_number_3_types from './number-3/assets/types/list-assets-number-3-types';
import delete_assets_number_3_types from './number-3/assets/types/delete-assets-number-3-types';
import create_number_3_attendancetransactions from './number-3/attendancetransactions/create-number-3-attendancetransactions';
import retrieve_number_3_attendancetransactions from './number-3/attendancetransactions/retrieve-number-3-attendancetransactions';
import update_number_3_attendancetransactions from './number-3/attendancetransactions/update-number-3-attendancetransactions';
import list_number_3_attendancetransactions from './number-3/attendancetransactions/list-number-3-attendancetransactions';
import delete_number_3_attendancetransactions from './number-3/attendancetransactions/delete-number-3-attendancetransactions';
import retrieve_by_date_and_code_number_3_attendancetransactions from './number-3/attendancetransactions/retrieve-by-date-and-code-number-3-attendancetransactions';
import create_number_3_contractaccruals from './number-3/contractaccruals/create-number-3-contractaccruals';
import retrieve_number_3_contractaccruals from './number-3/contractaccruals/retrieve-number-3-contractaccruals';
import update_number_3_contractaccruals from './number-3/contractaccruals/update-number-3-contractaccruals';
import list_number_3_contractaccruals from './number-3/contractaccruals/list-number-3-contractaccruals';
import delete_number_3_contractaccruals from './number-3/contractaccruals/delete-number-3-contractaccruals';
import create_number_3_contracts from './number-3/contracts/create-number-3-contracts';
import retrieve_number_3_contracts from './number-3/contracts/retrieve-number-3-contracts';
import update_number_3_contracts from './number-3/contracts/update-number-3-contracts';
import list_number_3_contracts from './number-3/contracts/list-number-3-contracts';
import create_invoice_number_3_contracts from './number-3/contracts/create-invoice-number-3-contracts';
import finish_number_3_contracts from './number-3/contracts/finish-number-3-contracts';
import increase_invoice_count_number_3_contracts from './number-3/contracts/increase-invoice-count-number-3-contracts';
import create_number_3_contracttemplates from './number-3/contracttemplates/create-number-3-contracttemplates';
import retrieve_number_3_contracttemplates from './number-3/contracttemplates/retrieve-number-3-contracttemplates';
import update_number_3_contracttemplates from './number-3/contracttemplates/update-number-3-contracttemplates';
import list_number_3_contracttemplates from './number-3/contracttemplates/list-number-3-contracttemplates';
import create_number_3_costcenters from './number-3/costcenters/create-number-3-costcenters';
import retrieve_number_3_costcenters from './number-3/costcenters/retrieve-number-3-costcenters';
import update_number_3_costcenters from './number-3/costcenters/update-number-3-costcenters';
import list_number_3_costcenters from './number-3/costcenters/list-number-3-costcenters';
import delete_number_3_costcenters from './number-3/costcenters/delete-number-3-costcenters';
import create_number_3_currencies from './number-3/currencies/create-number-3-currencies';
import retrieve_number_3_currencies from './number-3/currencies/retrieve-number-3-currencies';
import update_number_3_currencies from './number-3/currencies/update-number-3-currencies';
import list_number_3_currencies from './number-3/currencies/list-number-3-currencies';
import delete_number_3_currencies from './number-3/currencies/delete-number-3-currencies';
import create_number_3_customerreferences from './number-3/customerreferences/create-number-3-customerreferences';
import retrieve_number_3_customerreferences from './number-3/customerreferences/retrieve-number-3-customerreferences';
import update_number_3_customerreferences from './number-3/customerreferences/update-number-3-customerreferences';
import list_number_3_customerreferences from './number-3/customerreferences/list-number-3-customerreferences';
import delete_number_3_customerreferences from './number-3/customerreferences/delete-number-3-customerreferences';
import create_number_3_customers from './number-3/customers/create-number-3-customers';
import retrieve_number_3_customers from './number-3/customers/retrieve-number-3-customers';
import update_number_3_customers from './number-3/customers/update-number-3-customers';
import list_number_3_customers from './number-3/customers/list-number-3-customers';
import delete_number_3_customers from './number-3/customers/delete-number-3-customers';
import list_number_3_emailsenders from './number-3/emailsenders/list-number-3-emailsenders';
import delete_emailsenders_number_3_trusted from './number-3/emailsenders/trusted/delete-emailsenders-number-3-trusted';
import add_emailsenders_number_3_trusted from './number-3/emailsenders/trusted/add-emailsenders-number-3-trusted';
import create_number_3_employees from './number-3/employees/create-number-3-employees';
import retrieve_number_3_employees from './number-3/employees/retrieve-number-3-employees';
import update_number_3_employees from './number-3/employees/update-number-3-employees';
import list_number_3_employees from './number-3/employees/list-number-3-employees';
import create_number_3_expenses from './number-3/expenses/create-number-3-expenses';
import retrieve_number_3_expenses from './number-3/expenses/retrieve-number-3-expenses';
import list_number_3_expenses from './number-3/expenses/list-number-3-expenses';
import create_number_3_financialyears from './number-3/financialyears/create-number-3-financialyears';
import retrieve_number_3_financialyears from './number-3/financialyears/retrieve-number-3-financialyears';
import list_number_3_financialyears from './number-3/financialyears/list-number-3-financialyears';
import retrieve_number_3_inbox from './number-3/inbox/retrieve-number-3-inbox';
import remove_number_3_inbox from './number-3/inbox/remove-number-3-inbox';
import retrieve_file_number_3_inbox from './number-3/inbox/retrieve-file-number-3-inbox';
import upload_number_3_inbox from './number-3/inbox/upload-number-3-inbox';
import create_number_3_invoiceaccruals from './number-3/invoiceaccruals/create-number-3-invoiceaccruals';
import retrieve_number_3_invoiceaccruals from './number-3/invoiceaccruals/retrieve-number-3-invoiceaccruals';
import update_number_3_invoiceaccruals from './number-3/invoiceaccruals/update-number-3-invoiceaccruals';
import list_number_3_invoiceaccruals from './number-3/invoiceaccruals/list-number-3-invoiceaccruals';
import remove_number_3_invoiceaccruals from './number-3/invoiceaccruals/remove-number-3-invoiceaccruals';
import create_number_3_invoicepayments from './number-3/invoicepayments/create-number-3-invoicepayments';
import retrieve_number_3_invoicepayments from './number-3/invoicepayments/retrieve-number-3-invoicepayments';
import update_number_3_invoicepayments from './number-3/invoicepayments/update-number-3-invoicepayments';
import list_number_3_invoicepayments from './number-3/invoicepayments/list-number-3-invoicepayments';
import bookkeep_number_3_invoicepayments from './number-3/invoicepayments/bookkeep-number-3-invoicepayments';
import remove_number_3_invoicepayments from './number-3/invoicepayments/remove-number-3-invoicepayments';
import create_number_3_invoices from './number-3/invoices/create-number-3-invoices';
import retrieve_number_3_invoices from './number-3/invoices/retrieve-number-3-invoices';
import update_number_3_invoices from './number-3/invoices/update-number-3-invoices';
import list_number_3_invoices from './number-3/invoices/list-number-3-invoices';
import bookkeep_number_3_invoices from './number-3/invoices/bookkeep-number-3-invoices';
import cancel_number_3_invoices from './number-3/invoices/cancel-number-3-invoices';
import credit_number_3_invoices from './number-3/invoices/credit-number-3-invoices';
import preview_number_3_invoices from './number-3/invoices/preview-number-3-invoices';
import print_number_3_invoices from './number-3/invoices/print-number-3-invoices';
import print_reminder_number_3_invoices from './number-3/invoices/print-reminder-number-3-invoices';
import send_einvoice_number_3_invoices from './number-3/invoices/send-einvoice-number-3-invoices';
import send_email_number_3_invoices from './number-3/invoices/send-email-number-3-invoices';
import send_eprint_number_3_invoices from './number-3/invoices/send-eprint-number-3-invoices';
import set_done_number_3_invoices from './number-3/invoices/set-done-number-3-invoices';
import set_sent_number_3_invoices from './number-3/invoices/set-sent-number-3-invoices';
import create_number_3_labels from './number-3/labels/create-number-3-labels';
import update_number_3_labels from './number-3/labels/update-number-3-labels';
import list_number_3_labels from './number-3/labels/list-number-3-labels';
import delete_number_3_labels from './number-3/labels/delete-number-3-labels';
import create_number_3_modesofpayments from './number-3/modesofpayments/create-number-3-modesofpayments';
import retrieve_number_3_modesofpayments from './number-3/modesofpayments/retrieve-number-3-modesofpayments';
import update_number_3_modesofpayments from './number-3/modesofpayments/update-number-3-modesofpayments';
import list_number_3_modesofpayments from './number-3/modesofpayments/list-number-3-modesofpayments';
import delete_number_3_modesofpayments from './number-3/modesofpayments/delete-number-3-modesofpayments';
import retrieve_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/retrieve-number-3-noxfinansinvoices';
import pause_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/pause-number-3-noxfinansinvoices';
import report_payment_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/report-payment-number-3-noxfinansinvoices';
import send_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/send-number-3-noxfinansinvoices';
import stop_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/stop-number-3-noxfinansinvoices';
import take_fees_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/take-fees-number-3-noxfinansinvoices';
import unpause_number_3_noxfinansinvoices from './number-3/noxfinansinvoices/unpause-number-3-noxfinansinvoices';
import create_number_3_offers from './number-3/offers/create-number-3-offers';
import retrieve_number_3_offers from './number-3/offers/retrieve-number-3-offers';
import update_number_3_offers from './number-3/offers/update-number-3-offers';
import list_number_3_offers from './number-3/offers/list-number-3-offers';
import cancel_number_3_offers from './number-3/offers/cancel-number-3-offers';
import create_invoice_number_3_offers from './number-3/offers/create-invoice-number-3-offers';
import create_order_number_3_offers from './number-3/offers/create-order-number-3-offers';
import preview_number_3_offers from './number-3/offers/preview-number-3-offers';
import print_number_3_offers from './number-3/offers/print-number-3-offers';
import send_email_number_3_offers from './number-3/offers/send-email-number-3-offers';
import set_sent_number_3_offers from './number-3/offers/set-sent-number-3-offers';
import create_number_3_orders from './number-3/orders/create-number-3-orders';
import retrieve_number_3_orders from './number-3/orders/retrieve-number-3-orders';
import update_number_3_orders from './number-3/orders/update-number-3-orders';
import list_number_3_orders from './number-3/orders/list-number-3-orders';
import cancel_number_3_orders from './number-3/orders/cancel-number-3-orders';
import create_invoice_number_3_orders from './number-3/orders/create-invoice-number-3-orders';
import preview_number_3_orders from './number-3/orders/preview-number-3-orders';
import print_number_3_orders from './number-3/orders/print-number-3-orders';
import send_email_number_3_orders from './number-3/orders/send-email-number-3-orders';
import set_sent_number_3_orders from './number-3/orders/set-sent-number-3-orders';
import retrieve_number_3_predefinedaccounts from './number-3/predefinedaccounts/retrieve-number-3-predefinedaccounts';
import update_number_3_predefinedaccounts from './number-3/predefinedaccounts/update-number-3-predefinedaccounts';
import list_number_3_predefinedaccounts from './number-3/predefinedaccounts/list-number-3-predefinedaccounts';
import retrieve_number_3_predefinedvoucherseries from './number-3/predefinedvoucherseries/retrieve-number-3-predefinedvoucherseries';
import update_number_3_predefinedvoucherseries from './number-3/predefinedvoucherseries/update-number-3-predefinedvoucherseries';
import list_number_3_predefinedvoucherseries from './number-3/predefinedvoucherseries/list-number-3-predefinedvoucherseries';
import create_number_3_pricelists from './number-3/pricelists/create-number-3-pricelists';
import retrieve_number_3_pricelists from './number-3/pricelists/retrieve-number-3-pricelists';
import update_number_3_pricelists from './number-3/pricelists/update-number-3-pricelists';
import list_number_3_pricelists from './number-3/pricelists/list-number-3-pricelists';
import create_number_3_prices from './number-3/prices/create-number-3-prices';
import retrieve_number_3_prices from './number-3/prices/retrieve-number-3-prices';
import update_number_3_prices from './number-3/prices/update-number-3-prices';
import list_number_3_prices from './number-3/prices/list-number-3-prices';
import delete_number_3_prices from './number-3/prices/delete-number-3-prices';
import retrieve_first_number_3_prices from './number-3/prices/retrieve-first-number-3-prices';
import retrieve_sublist_number_3_prices from './number-3/prices/retrieve-sublist-number-3-prices';
import update_first_number_3_prices from './number-3/prices/update-first-number-3-prices';
import create_number_3_projects from './number-3/projects/create-number-3-projects';
import retrieve_number_3_projects from './number-3/projects/retrieve-number-3-projects';
import update_number_3_projects from './number-3/projects/update-number-3-projects';
import list_number_3_projects from './number-3/projects/list-number-3-projects';
import delete_number_3_projects from './number-3/projects/delete-number-3-projects';
import create_number_3_salarytransactions from './number-3/salarytransactions/create-number-3-salarytransactions';
import retrieve_number_3_salarytransactions from './number-3/salarytransactions/retrieve-number-3-salarytransactions';
import update_number_3_salarytransactions from './number-3/salarytransactions/update-number-3-salarytransactions';
import list_number_3_salarytransactions from './number-3/salarytransactions/list-number-3-salarytransactions';
import delete_number_3_salarytransactions from './number-3/salarytransactions/delete-number-3-salarytransactions';
import retrieve_number_3_scheduletimes from './number-3/scheduletimes/retrieve-number-3-scheduletimes';
import update_number_3_scheduletimes from './number-3/scheduletimes/update-number-3-scheduletimes';
import reset_day_number_3_scheduletimes from './number-3/scheduletimes/reset-day-number-3-scheduletimes';
import retrieve_company_number_3_settings from './number-3/settings/retrieve-company-number-3-settings';
import retrieve_locked_period_number_3_settings from './number-3/settings/retrieve-locked-period-number-3-settings';
import create_number_3_supplierinvoiceaccruals from './number-3/supplierinvoiceaccruals/create-number-3-supplierinvoiceaccruals';
import retrieve_number_3_supplierinvoiceaccruals from './number-3/supplierinvoiceaccruals/retrieve-number-3-supplierinvoiceaccruals';
import update_number_3_supplierinvoiceaccruals from './number-3/supplierinvoiceaccruals/update-number-3-supplierinvoiceaccruals';
import list_number_3_supplierinvoiceaccruals from './number-3/supplierinvoiceaccruals/list-number-3-supplierinvoiceaccruals';
import delete_number_3_supplierinvoiceaccruals from './number-3/supplierinvoiceaccruals/delete-number-3-supplierinvoiceaccruals';
import create_number_3_supplierinvoiceexternalurlconnections from './number-3/supplierinvoiceexternalurlconnections/create-number-3-supplierinvoiceexternalurlconnections';
import retrieve_number_3_supplierinvoiceexternalurlconnections from './number-3/supplierinvoiceexternalurlconnections/retrieve-number-3-supplierinvoiceexternalurlconnections';
import update_number_3_supplierinvoiceexternalurlconnections from './number-3/supplierinvoiceexternalurlconnections/update-number-3-supplierinvoiceexternalurlconnections';
import delete_number_3_supplierinvoiceexternalurlconnections from './number-3/supplierinvoiceexternalurlconnections/delete-number-3-supplierinvoiceexternalurlconnections';
import create_number_3_supplierinvoicefileconnections from './number-3/supplierinvoicefileconnections/create-number-3-supplierinvoicefileconnections';
import retrieve_number_3_supplierinvoicefileconnections from './number-3/supplierinvoicefileconnections/retrieve-number-3-supplierinvoicefileconnections';
import list_number_3_supplierinvoicefileconnections from './number-3/supplierinvoicefileconnections/list-number-3-supplierinvoicefileconnections';
import delete_number_3_supplierinvoicefileconnections from './number-3/supplierinvoicefileconnections/delete-number-3-supplierinvoicefileconnections';
import create_number_3_supplierinvoicepayments from './number-3/supplierinvoicepayments/create-number-3-supplierinvoicepayments';
import retrieve_number_3_supplierinvoicepayments from './number-3/supplierinvoicepayments/retrieve-number-3-supplierinvoicepayments';
import update_number_3_supplierinvoicepayments from './number-3/supplierinvoicepayments/update-number-3-supplierinvoicepayments';
import list_number_3_supplierinvoicepayments from './number-3/supplierinvoicepayments/list-number-3-supplierinvoicepayments';
import delete_number_3_supplierinvoicepayments from './number-3/supplierinvoicepayments/delete-number-3-supplierinvoicepayments';
import bookkeep_number_3_supplierinvoicepayments from './number-3/supplierinvoicepayments/bookkeep-number-3-supplierinvoicepayments';
import create_number_3_supplierinvoices from './number-3/supplierinvoices/create-number-3-supplierinvoices';
import retrieve_number_3_supplierinvoices from './number-3/supplierinvoices/retrieve-number-3-supplierinvoices';
import update_number_3_supplierinvoices from './number-3/supplierinvoices/update-number-3-supplierinvoices';
import list_number_3_supplierinvoices from './number-3/supplierinvoices/list-number-3-supplierinvoices';
import update_approvalbookkeep_number_3_supplierinvoices from './number-3/supplierinvoices/update-approvalbookkeep-number-3-supplierinvoices';
import update_approvalpayment_number_3_supplierinvoices from './number-3/supplierinvoices/update-approvalpayment-number-3-supplierinvoices';
import update_bookkeep_number_3_supplierinvoices from './number-3/supplierinvoices/update-bookkeep-number-3-supplierinvoices';
import update_cancel_number_3_supplierinvoices from './number-3/supplierinvoices/update-cancel-number-3-supplierinvoices';
import update_credit_number_3_supplierinvoices from './number-3/supplierinvoices/update-credit-number-3-supplierinvoices';
import create_number_3_suppliers from './number-3/suppliers/create-number-3-suppliers';
import retrieve_number_3_suppliers from './number-3/suppliers/retrieve-number-3-suppliers';
import update_number_3_suppliers from './number-3/suppliers/update-number-3-suppliers';
import list_number_3_suppliers from './number-3/suppliers/list-number-3-suppliers';
import create_number_3_taxreductions from './number-3/taxreductions/create-number-3-taxreductions';
import retrieve_number_3_taxreductions from './number-3/taxreductions/retrieve-number-3-taxreductions';
import update_number_3_taxreductions from './number-3/taxreductions/update-number-3-taxreductions';
import list_number_3_taxreductions from './number-3/taxreductions/list-number-3-taxreductions';
import delete_number_3_taxreductions from './number-3/taxreductions/delete-number-3-taxreductions';
import create_number_3_termsofdeliveries from './number-3/termsofdeliveries/create-number-3-termsofdeliveries';
import retrieve_number_3_termsofdeliveries from './number-3/termsofdeliveries/retrieve-number-3-termsofdeliveries';
import update_number_3_termsofdeliveries from './number-3/termsofdeliveries/update-number-3-termsofdeliveries';
import list_number_3_termsofdeliveries from './number-3/termsofdeliveries/list-number-3-termsofdeliveries';
import create_number_3_termsofpayments from './number-3/termsofpayments/create-number-3-termsofpayments';
import retrieve_number_3_termsofpayments from './number-3/termsofpayments/retrieve-number-3-termsofpayments';
import update_number_3_termsofpayments from './number-3/termsofpayments/update-number-3-termsofpayments';
import list_number_3_termsofpayments from './number-3/termsofpayments/list-number-3-termsofpayments';
import delete_number_3_termsofpayments from './number-3/termsofpayments/delete-number-3-termsofpayments';
import create_number_3_units from './number-3/units/create-number-3-units';
import retrieve_number_3_units from './number-3/units/retrieve-number-3-units';
import update_number_3_units from './number-3/units/update-number-3-units';
import list_number_3_units from './number-3/units/list-number-3-units';
import delete_number_3_units from './number-3/units/delete-number-3-units';
import create_number_3_voucherfileconnections from './number-3/voucherfileconnections/create-number-3-voucherfileconnections';
import retrieve_number_3_voucherfileconnections from './number-3/voucherfileconnections/retrieve-number-3-voucherfileconnections';
import list_number_3_voucherfileconnections from './number-3/voucherfileconnections/list-number-3-voucherfileconnections';
import delete_number_3_voucherfileconnections from './number-3/voucherfileconnections/delete-number-3-voucherfileconnections';
import create_number_3_vouchers from './number-3/vouchers/create-number-3-vouchers';
import retrieve_number_3_vouchers from './number-3/vouchers/retrieve-number-3-vouchers';
import list_number_3_vouchers from './number-3/vouchers/list-number-3-vouchers';
import retrieve_vouchers_number_3_sublist from './number-3/vouchers/sublist/retrieve-vouchers-number-3-sublist';
import list_vouchers_number_3_sublist from './number-3/vouchers/sublist/list-vouchers-number-3-sublist';
import create_number_3_voucherseries from './number-3/voucherseries/create-number-3-voucherseries';
import retrieve_number_3_voucherseries from './number-3/voucherseries/retrieve-number-3-voucherseries';
import update_number_3_voucherseries from './number-3/voucherseries/update-number-3-voucherseries';
import list_number_3_voucherseries from './number-3/voucherseries/list-number-3-voucherseries';
import create_number_3_wayofdeliveries from './number-3/wayofdeliveries/create-number-3-wayofdeliveries';
import retrieve_number_3_wayofdeliveries from './number-3/wayofdeliveries/retrieve-number-3-wayofdeliveries';
import update_number_3_wayofdeliveries from './number-3/wayofdeliveries/update-number-3-wayofdeliveries';
import list_number_3_wayofdeliveries from './number-3/wayofdeliveries/list-number-3-wayofdeliveries';
import delete_number_3_wayofdeliveries from './number-3/wayofdeliveries/delete-number-3-wayofdeliveries';
import create_fileattachments_api_attachments_v1 from './api/fileattachments/attachments-v1/create-fileattachments-api-attachments-v1';
import update_fileattachments_api_attachments_v1 from './api/fileattachments/attachments-v1/update-fileattachments-api-attachments-v1';
import list_fileattachments_api_attachments_v1 from './api/fileattachments/attachments-v1/list-fileattachments-api-attachments-v1';
import delete_fileattachments_api_attachments_v1 from './api/fileattachments/attachments-v1/delete-fileattachments-api-attachments-v1';
import count_fileattachments_api_attachments_v1 from './api/fileattachments/attachments-v1/count-fileattachments-api-attachments-v1';
import validate_fileattachments_api_attachments_v1 from './api/fileattachments/attachments-v1/validate-fileattachments-api-attachments-v1';
import get_sales_info_api_integration_developer from './api/integration-developer/get-sales-info-api-integration-developer';
import list_ratings_api_integration_developer from './api/integration-developer/list-ratings-api-integration-developer';
import get_user_info_integration_developer_api_users from './api/integration-developer/users/get-user-info-integration-developer-api-users';
import get_sales_info_apps_integration_partner_api_sales_v1 from './api/integration-partner/apps/sales-v1/get-sales-info-apps-integration-partner-api-sales-v1';
import get_sales_info_for_tenant_apps_integration_partner_api_sales_v1 from './api/integration-partner/apps/sales-v1/get-sales-info-for-tenant-apps-integration-partner-api-sales-v1';
import get_articles_api_time from './api/time/get-articles-api-time';
import get_registrations_api_time from './api/time/get-registrations-api-time';
import retrieve_tenants_v4_api_warehouse from './api/warehouse/retrieve-tenants-v4-api-warehouse';
import retrieve_deliveries_v1_warehouse_api_deliveries_v1 from './api/warehouse/deliveries-v1/retrieve-deliveries-v1-warehouse-api-deliveries-v1';
import create_deliveries_v1_warehouse_api_inbounddeliveries from './api/warehouse/deliveries-v1/inbounddeliveries/create-deliveries-v1-warehouse-api-inbounddeliveries';
import retrieve_deliveries_v1_warehouse_api_inbounddeliveries from './api/warehouse/deliveries-v1/inbounddeliveries/retrieve-deliveries-v1-warehouse-api-inbounddeliveries';
import update_deliveries_v1_warehouse_api_inbounddeliveries from './api/warehouse/deliveries-v1/inbounddeliveries/update-deliveries-v1-warehouse-api-inbounddeliveries';
import update_release_deliveries_v1_warehouse_api_inbounddeliveries from './api/warehouse/deliveries-v1/inbounddeliveries/update-release-deliveries-v1-warehouse-api-inbounddeliveries';
import update_void_deliveries_v1_warehouse_api_inbounddeliveries from './api/warehouse/deliveries-v1/inbounddeliveries/update-void-deliveries-v1-warehouse-api-inbounddeliveries';
import create_deliveries_v1_warehouse_api_outbounddeliveries from './api/warehouse/deliveries-v1/outbounddeliveries/create-deliveries-v1-warehouse-api-outbounddeliveries';
import retrieve_deliveries_v1_warehouse_api_outbounddeliveries from './api/warehouse/deliveries-v1/outbounddeliveries/retrieve-deliveries-v1-warehouse-api-outbounddeliveries';
import update_deliveries_v1_warehouse_api_outbounddeliveries from './api/warehouse/deliveries-v1/outbounddeliveries/update-deliveries-v1-warehouse-api-outbounddeliveries';
import update_release_deliveries_v1_warehouse_api_outbounddeliveries from './api/warehouse/deliveries-v1/outbounddeliveries/update-release-deliveries-v1-warehouse-api-outbounddeliveries';
import update_void_deliveries_v1_warehouse_api_outbounddeliveries from './api/warehouse/deliveries-v1/outbounddeliveries/update-void-deliveries-v1-warehouse-api-outbounddeliveries';
import retrieve_custom_documentdeliveries_warehouse_api_documenttypes_v1 from './api/warehouse/documentdeliveries/custom/documenttypes-v1/retrieve-custom-documentdeliveries-warehouse-api-documenttypes-v1';
import documenttypes_v1_custom_documentdeliveries_warehouse_api_documenttypes_v1 from './api/warehouse/documentdeliveries/custom/documenttypes-v1/documenttypes-v1-custom-documentdeliveries-warehouse-api-documenttypes-v1';
import retrieve_documenttypes_v1_custom_documentdeliveries_warehouse_api_documenttypes_v1 from './api/warehouse/documentdeliveries/custom/documenttypes-v1/retrieve-documenttypes-v1-custom-documentdeliveries-warehouse-api-documenttypes-v1';
import retrieve_custom_documentdeliveries_warehouse_api_inbound_v1 from './api/warehouse/documentdeliveries/custom/inbound-v1/retrieve-custom-documentdeliveries-warehouse-api-inbound-v1';
import update_custom_documentdeliveries_warehouse_api_inbound_v1 from './api/warehouse/documentdeliveries/custom/inbound-v1/update-custom-documentdeliveries-warehouse-api-inbound-v1';
import update_release_custom_documentdeliveries_warehouse_api_inbound_v1 from './api/warehouse/documentdeliveries/custom/inbound-v1/update-release-custom-documentdeliveries-warehouse-api-inbound-v1';
import update_void_custom_documentdeliveries_warehouse_api_inbound_v1 from './api/warehouse/documentdeliveries/custom/inbound-v1/update-void-custom-documentdeliveries-warehouse-api-inbound-v1';
import retrieve_custom_documentdeliveries_warehouse_api_outbound_v1 from './api/warehouse/documentdeliveries/custom/outbound-v1/retrieve-custom-documentdeliveries-warehouse-api-outbound-v1';
import update_custom_documentdeliveries_warehouse_api_outbound_v1 from './api/warehouse/documentdeliveries/custom/outbound-v1/update-custom-documentdeliveries-warehouse-api-outbound-v1';
import update_release_custom_documentdeliveries_warehouse_api_outbound_v1 from './api/warehouse/documentdeliveries/custom/outbound-v1/update-release-custom-documentdeliveries-warehouse-api-outbound-v1';
import update_void_custom_documentdeliveries_warehouse_api_outbound_v1 from './api/warehouse/documentdeliveries/custom/outbound-v1/update-void-custom-documentdeliveries-warehouse-api-outbound-v1';
import retrieve_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/retrieve-warehouse-api-incominggoods-v1';
import update_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/update-warehouse-api-incominggoods-v1';
import incominggoods_v1_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/incominggoods-v1-warehouse-api-incominggoods-v1';
import retrieve_incominggoods_v1_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/retrieve-incominggoods-v1-warehouse-api-incominggoods-v1';
import update_completed_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/update-completed-warehouse-api-incominggoods-v1';
import update_release_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/update-release-warehouse-api-incominggoods-v1';
import update_void_warehouse_api_incominggoods_v1 from './api/warehouse/incominggoods-v1/update-void-warehouse-api-incominggoods-v1';
import retrieve_warehouse_api_productionorders_v1 from './api/warehouse/productionorders-v1/retrieve-warehouse-api-productionorders-v1';
import update_warehouse_api_productionorders_v1 from './api/warehouse/productionorders-v1/update-warehouse-api-productionorders-v1';
import productionorders_v1_warehouse_api_productionorders_v1 from './api/warehouse/productionorders-v1/productionorders-v1-warehouse-api-productionorders-v1';
import retrieve_productionorders_v1_warehouse_api_productionorders_v1 from './api/warehouse/productionorders-v1/retrieve-productionorders-v1-warehouse-api-productionorders-v1';
import retrieve_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/retrieve-warehouse-api-purchaseorders-v1';
import update_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/update-warehouse-api-purchaseorders-v1';
import purchaseorders_v1_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/purchaseorders-v1-warehouse-api-purchaseorders-v1';
import retrieve_csv_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/retrieve-csv-warehouse-api-purchaseorders-v1';
import retrieve_matches_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/retrieve-matches-warehouse-api-purchaseorders-v1';
import retrieve_notes_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/retrieve-notes-warehouse-api-purchaseorders-v1';
import retrieve_purchaseorders_v1_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/retrieve-purchaseorders-v1-warehouse-api-purchaseorders-v1';
import send_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/send-warehouse-api-purchaseorders-v1';
import sendpurchaseorders_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/sendpurchaseorders-warehouse-api-purchaseorders-v1';
import update_complete_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/update-complete-warehouse-api-purchaseorders-v1';
import update_dropshipcomplete_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/update-dropshipcomplete-warehouse-api-purchaseorders-v1';
import update_partial_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/update-partial-warehouse-api-purchaseorders-v1';
import update_void_warehouse_api_purchaseorders_v1 from './api/warehouse/purchaseorders-v1/update-void-warehouse-api-purchaseorders-v1';
import create_purchaseorders_v1_warehouse_api_response from './api/warehouse/purchaseorders-v1/response/create-purchaseorders-v1-warehouse-api-response';
import retrieve_stockbalance_warehouse_api_status_v1 from './api/warehouse/status-v1/retrieve-stockbalance-warehouse-api-status-v1';
import retrieve_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/retrieve-warehouse-api-stockpoints-v1';
import update_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/update-warehouse-api-stockpoints-v1';
import delete_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/delete-warehouse-api-stockpoints-v1';
import retrieve_multi_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/retrieve-multi-warehouse-api-stockpoints-v1';
import retrieve_stocklocations_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/retrieve-stocklocations-warehouse-api-stockpoints-v1';
import retrieve_stockpoints_v1_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/retrieve-stockpoints-v1-warehouse-api-stockpoints-v1';
import stockpoints_v1_warehouse_api_stockpoints_v1 from './api/warehouse/stockpoints-v1/stockpoints-v1-warehouse-api-stockpoints-v1';
import retrieve_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/retrieve-warehouse-api-stocktaking-v1';
import update_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/update-warehouse-api-stocktaking-v1';
import delete_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/delete-warehouse-api-stocktaking-v1';
import addrows_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/addrows-warehouse-api-stocktaking-v1';
import retrieve_candidates_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/retrieve-candidates-warehouse-api-stocktaking-v1';
import retrieve_stocktaking_v1_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/retrieve-stocktaking-v1-warehouse-api-stocktaking-v1';
import stocktaking_v1_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/stocktaking-v1-warehouse-api-stocktaking-v1';
import update_release_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/update-release-warehouse-api-stocktaking-v1';
import update_void_warehouse_api_stocktaking_v1 from './api/warehouse/stocktaking-v1/update-void-warehouse-api-stocktaking-v1';
import create_stocktaking_v1_warehouse_api_rows from './api/warehouse/stocktaking-v1/rows/create-stocktaking-v1-warehouse-api-rows';
import list_stocktaking_v1_warehouse_api_rows from './api/warehouse/stocktaking-v1/rows/list-stocktaking-v1-warehouse-api-rows';
import delete_stocktaking_v1_warehouse_api_rows from './api/warehouse/stocktaking-v1/rows/delete-stocktaking-v1-warehouse-api-rows';
import delete_all_stocktaking_v1_warehouse_api_rows from './api/warehouse/stocktaking-v1/rows/delete-all-stocktaking-v1-warehouse-api-rows';
import retrieve_warehouse_api_stocktransfer_v1 from './api/warehouse/stocktransfer-v1/retrieve-warehouse-api-stocktransfer-v1';
import update_warehouse_api_stocktransfer_v1 from './api/warehouse/stocktransfer-v1/update-warehouse-api-stocktransfer-v1';
import stocktransfer_v1_warehouse_api_stocktransfer_v1 from './api/warehouse/stocktransfer-v1/stocktransfer-v1-warehouse-api-stocktransfer-v1';
import update_release_warehouse_api_stocktransfer_v1 from './api/warehouse/stocktransfer-v1/update-release-warehouse-api-stocktransfer-v1';
import update_void_warehouse_api_stocktransfer_v1 from './api/warehouse/stocktransfer-v1/update-void-warehouse-api-stocktransfer-v1';

export const endpoints: Endpoint[] = [];

function addEndpoint(endpoint: Endpoint) {
  endpoints.push(endpoint);
}

addEndpoint(list_account_charts_number_3);
addEndpoint(list_print_templates_number_3);
addEndpoint(retrieve_company_information_number_3);
addEndpoint(retrieve_eu_vat_limit_regulation_number_3);
addEndpoint(retrieve_sie_file_number_3);
addEndpoint(retrieve_user_information_number_3);
addEndpoint(retrieve_vacation_debt_basis_number_3);
addEndpoint(create_number_3_absencetransactions);
addEndpoint(retrieve_number_3_absencetransactions);
addEndpoint(update_number_3_absencetransactions);
addEndpoint(list_number_3_absencetransactions);
addEndpoint(delete_number_3_absencetransactions);
addEndpoint(retrieve_by_date_and_code_number_3_absencetransactions);
addEndpoint(create_number_3_accounts);
addEndpoint(retrieve_number_3_accounts);
addEndpoint(update_number_3_accounts);
addEndpoint(list_number_3_accounts);
addEndpoint(delete_number_3_accounts);
addEndpoint(retrieve_number_3_archive);
addEndpoint(delete_file_number_3_archive);
addEndpoint(remove_files_number_3_archive);
addEndpoint(retrieve_file_number_3_archive);
addEndpoint(upload_file_number_3_archive);
addEndpoint(create_number_3_articlefileconnections);
addEndpoint(retrieve_number_3_articlefileconnections);
addEndpoint(list_number_3_articlefileconnections);
addEndpoint(remove_number_3_articlefileconnections);
addEndpoint(create_number_3_articles);
addEndpoint(retrieve_number_3_articles);
addEndpoint(update_number_3_articles);
addEndpoint(list_number_3_articles);
addEndpoint(delete_number_3_articles);
addEndpoint(create_number_3_articleurlconnections);
addEndpoint(retrieve_number_3_articleurlconnections);
addEndpoint(update_number_3_articleurlconnections);
addEndpoint(list_number_3_articleurlconnections);
addEndpoint(remove_number_3_articleurlconnections);
addEndpoint(create_number_3_assetfileconnections);
addEndpoint(list_number_3_assetfileconnections);
addEndpoint(delete_number_3_assetfileconnections);
addEndpoint(create_number_3_assets);
addEndpoint(retrieve_number_3_assets);
addEndpoint(update_number_3_assets);
addEndpoint(list_number_3_assets);
addEndpoint(delete_number_3_assets);
addEndpoint(change_ob_number_3_assets);
addEndpoint(depreciate_number_3_assets);
addEndpoint(list_depreciations_number_3_assets);
addEndpoint(scrap_number_3_assets);
addEndpoint(sell_number_3_assets);
addEndpoint(write_down_number_3_assets);
addEndpoint(write_up_number_3_assets);
addEndpoint(create_assets_number_3_types);
addEndpoint(retrieve_assets_number_3_types);
addEndpoint(update_assets_number_3_types);
addEndpoint(list_assets_number_3_types);
addEndpoint(delete_assets_number_3_types);
addEndpoint(create_number_3_attendancetransactions);
addEndpoint(retrieve_number_3_attendancetransactions);
addEndpoint(update_number_3_attendancetransactions);
addEndpoint(list_number_3_attendancetransactions);
addEndpoint(delete_number_3_attendancetransactions);
addEndpoint(retrieve_by_date_and_code_number_3_attendancetransactions);
addEndpoint(create_number_3_contractaccruals);
addEndpoint(retrieve_number_3_contractaccruals);
addEndpoint(update_number_3_contractaccruals);
addEndpoint(list_number_3_contractaccruals);
addEndpoint(delete_number_3_contractaccruals);
addEndpoint(create_number_3_contracts);
addEndpoint(retrieve_number_3_contracts);
addEndpoint(update_number_3_contracts);
addEndpoint(list_number_3_contracts);
addEndpoint(create_invoice_number_3_contracts);
addEndpoint(finish_number_3_contracts);
addEndpoint(increase_invoice_count_number_3_contracts);
addEndpoint(create_number_3_contracttemplates);
addEndpoint(retrieve_number_3_contracttemplates);
addEndpoint(update_number_3_contracttemplates);
addEndpoint(list_number_3_contracttemplates);
addEndpoint(create_number_3_costcenters);
addEndpoint(retrieve_number_3_costcenters);
addEndpoint(update_number_3_costcenters);
addEndpoint(list_number_3_costcenters);
addEndpoint(delete_number_3_costcenters);
addEndpoint(create_number_3_currencies);
addEndpoint(retrieve_number_3_currencies);
addEndpoint(update_number_3_currencies);
addEndpoint(list_number_3_currencies);
addEndpoint(delete_number_3_currencies);
addEndpoint(create_number_3_customerreferences);
addEndpoint(retrieve_number_3_customerreferences);
addEndpoint(update_number_3_customerreferences);
addEndpoint(list_number_3_customerreferences);
addEndpoint(delete_number_3_customerreferences);
addEndpoint(create_number_3_customers);
addEndpoint(retrieve_number_3_customers);
addEndpoint(update_number_3_customers);
addEndpoint(list_number_3_customers);
addEndpoint(delete_number_3_customers);
addEndpoint(list_number_3_emailsenders);
addEndpoint(delete_emailsenders_number_3_trusted);
addEndpoint(add_emailsenders_number_3_trusted);
addEndpoint(create_number_3_employees);
addEndpoint(retrieve_number_3_employees);
addEndpoint(update_number_3_employees);
addEndpoint(list_number_3_employees);
addEndpoint(create_number_3_expenses);
addEndpoint(retrieve_number_3_expenses);
addEndpoint(list_number_3_expenses);
addEndpoint(create_number_3_financialyears);
addEndpoint(retrieve_number_3_financialyears);
addEndpoint(list_number_3_financialyears);
addEndpoint(retrieve_number_3_inbox);
addEndpoint(remove_number_3_inbox);
addEndpoint(retrieve_file_number_3_inbox);
addEndpoint(upload_number_3_inbox);
addEndpoint(create_number_3_invoiceaccruals);
addEndpoint(retrieve_number_3_invoiceaccruals);
addEndpoint(update_number_3_invoiceaccruals);
addEndpoint(list_number_3_invoiceaccruals);
addEndpoint(remove_number_3_invoiceaccruals);
addEndpoint(create_number_3_invoicepayments);
addEndpoint(retrieve_number_3_invoicepayments);
addEndpoint(update_number_3_invoicepayments);
addEndpoint(list_number_3_invoicepayments);
addEndpoint(bookkeep_number_3_invoicepayments);
addEndpoint(remove_number_3_invoicepayments);
addEndpoint(create_number_3_invoices);
addEndpoint(retrieve_number_3_invoices);
addEndpoint(update_number_3_invoices);
addEndpoint(list_number_3_invoices);
addEndpoint(bookkeep_number_3_invoices);
addEndpoint(cancel_number_3_invoices);
addEndpoint(credit_number_3_invoices);
addEndpoint(preview_number_3_invoices);
addEndpoint(print_number_3_invoices);
addEndpoint(print_reminder_number_3_invoices);
addEndpoint(send_einvoice_number_3_invoices);
addEndpoint(send_email_number_3_invoices);
addEndpoint(send_eprint_number_3_invoices);
addEndpoint(set_done_number_3_invoices);
addEndpoint(set_sent_number_3_invoices);
addEndpoint(create_number_3_labels);
addEndpoint(update_number_3_labels);
addEndpoint(list_number_3_labels);
addEndpoint(delete_number_3_labels);
addEndpoint(create_number_3_modesofpayments);
addEndpoint(retrieve_number_3_modesofpayments);
addEndpoint(update_number_3_modesofpayments);
addEndpoint(list_number_3_modesofpayments);
addEndpoint(delete_number_3_modesofpayments);
addEndpoint(retrieve_number_3_noxfinansinvoices);
addEndpoint(pause_number_3_noxfinansinvoices);
addEndpoint(report_payment_number_3_noxfinansinvoices);
addEndpoint(send_number_3_noxfinansinvoices);
addEndpoint(stop_number_3_noxfinansinvoices);
addEndpoint(take_fees_number_3_noxfinansinvoices);
addEndpoint(unpause_number_3_noxfinansinvoices);
addEndpoint(create_number_3_offers);
addEndpoint(retrieve_number_3_offers);
addEndpoint(update_number_3_offers);
addEndpoint(list_number_3_offers);
addEndpoint(cancel_number_3_offers);
addEndpoint(create_invoice_number_3_offers);
addEndpoint(create_order_number_3_offers);
addEndpoint(preview_number_3_offers);
addEndpoint(print_number_3_offers);
addEndpoint(send_email_number_3_offers);
addEndpoint(set_sent_number_3_offers);
addEndpoint(create_number_3_orders);
addEndpoint(retrieve_number_3_orders);
addEndpoint(update_number_3_orders);
addEndpoint(list_number_3_orders);
addEndpoint(cancel_number_3_orders);
addEndpoint(create_invoice_number_3_orders);
addEndpoint(preview_number_3_orders);
addEndpoint(print_number_3_orders);
addEndpoint(send_email_number_3_orders);
addEndpoint(set_sent_number_3_orders);
addEndpoint(retrieve_number_3_predefinedaccounts);
addEndpoint(update_number_3_predefinedaccounts);
addEndpoint(list_number_3_predefinedaccounts);
addEndpoint(retrieve_number_3_predefinedvoucherseries);
addEndpoint(update_number_3_predefinedvoucherseries);
addEndpoint(list_number_3_predefinedvoucherseries);
addEndpoint(create_number_3_pricelists);
addEndpoint(retrieve_number_3_pricelists);
addEndpoint(update_number_3_pricelists);
addEndpoint(list_number_3_pricelists);
addEndpoint(create_number_3_prices);
addEndpoint(retrieve_number_3_prices);
addEndpoint(update_number_3_prices);
addEndpoint(list_number_3_prices);
addEndpoint(delete_number_3_prices);
addEndpoint(retrieve_first_number_3_prices);
addEndpoint(retrieve_sublist_number_3_prices);
addEndpoint(update_first_number_3_prices);
addEndpoint(create_number_3_projects);
addEndpoint(retrieve_number_3_projects);
addEndpoint(update_number_3_projects);
addEndpoint(list_number_3_projects);
addEndpoint(delete_number_3_projects);
addEndpoint(create_number_3_salarytransactions);
addEndpoint(retrieve_number_3_salarytransactions);
addEndpoint(update_number_3_salarytransactions);
addEndpoint(list_number_3_salarytransactions);
addEndpoint(delete_number_3_salarytransactions);
addEndpoint(retrieve_number_3_scheduletimes);
addEndpoint(update_number_3_scheduletimes);
addEndpoint(reset_day_number_3_scheduletimes);
addEndpoint(retrieve_company_number_3_settings);
addEndpoint(retrieve_locked_period_number_3_settings);
addEndpoint(create_number_3_supplierinvoiceaccruals);
addEndpoint(retrieve_number_3_supplierinvoiceaccruals);
addEndpoint(update_number_3_supplierinvoiceaccruals);
addEndpoint(list_number_3_supplierinvoiceaccruals);
addEndpoint(delete_number_3_supplierinvoiceaccruals);
addEndpoint(create_number_3_supplierinvoiceexternalurlconnections);
addEndpoint(retrieve_number_3_supplierinvoiceexternalurlconnections);
addEndpoint(update_number_3_supplierinvoiceexternalurlconnections);
addEndpoint(delete_number_3_supplierinvoiceexternalurlconnections);
addEndpoint(create_number_3_supplierinvoicefileconnections);
addEndpoint(retrieve_number_3_supplierinvoicefileconnections);
addEndpoint(list_number_3_supplierinvoicefileconnections);
addEndpoint(delete_number_3_supplierinvoicefileconnections);
addEndpoint(create_number_3_supplierinvoicepayments);
addEndpoint(retrieve_number_3_supplierinvoicepayments);
addEndpoint(update_number_3_supplierinvoicepayments);
addEndpoint(list_number_3_supplierinvoicepayments);
addEndpoint(delete_number_3_supplierinvoicepayments);
addEndpoint(bookkeep_number_3_supplierinvoicepayments);
addEndpoint(create_number_3_supplierinvoices);
addEndpoint(retrieve_number_3_supplierinvoices);
addEndpoint(update_number_3_supplierinvoices);
addEndpoint(list_number_3_supplierinvoices);
addEndpoint(update_approvalbookkeep_number_3_supplierinvoices);
addEndpoint(update_approvalpayment_number_3_supplierinvoices);
addEndpoint(update_bookkeep_number_3_supplierinvoices);
addEndpoint(update_cancel_number_3_supplierinvoices);
addEndpoint(update_credit_number_3_supplierinvoices);
addEndpoint(create_number_3_suppliers);
addEndpoint(retrieve_number_3_suppliers);
addEndpoint(update_number_3_suppliers);
addEndpoint(list_number_3_suppliers);
addEndpoint(create_number_3_taxreductions);
addEndpoint(retrieve_number_3_taxreductions);
addEndpoint(update_number_3_taxreductions);
addEndpoint(list_number_3_taxreductions);
addEndpoint(delete_number_3_taxreductions);
addEndpoint(create_number_3_termsofdeliveries);
addEndpoint(retrieve_number_3_termsofdeliveries);
addEndpoint(update_number_3_termsofdeliveries);
addEndpoint(list_number_3_termsofdeliveries);
addEndpoint(create_number_3_termsofpayments);
addEndpoint(retrieve_number_3_termsofpayments);
addEndpoint(update_number_3_termsofpayments);
addEndpoint(list_number_3_termsofpayments);
addEndpoint(delete_number_3_termsofpayments);
addEndpoint(create_number_3_units);
addEndpoint(retrieve_number_3_units);
addEndpoint(update_number_3_units);
addEndpoint(list_number_3_units);
addEndpoint(delete_number_3_units);
addEndpoint(create_number_3_voucherfileconnections);
addEndpoint(retrieve_number_3_voucherfileconnections);
addEndpoint(list_number_3_voucherfileconnections);
addEndpoint(delete_number_3_voucherfileconnections);
addEndpoint(create_number_3_vouchers);
addEndpoint(retrieve_number_3_vouchers);
addEndpoint(list_number_3_vouchers);
addEndpoint(retrieve_vouchers_number_3_sublist);
addEndpoint(list_vouchers_number_3_sublist);
addEndpoint(create_number_3_voucherseries);
addEndpoint(retrieve_number_3_voucherseries);
addEndpoint(update_number_3_voucherseries);
addEndpoint(list_number_3_voucherseries);
addEndpoint(create_number_3_wayofdeliveries);
addEndpoint(retrieve_number_3_wayofdeliveries);
addEndpoint(update_number_3_wayofdeliveries);
addEndpoint(list_number_3_wayofdeliveries);
addEndpoint(delete_number_3_wayofdeliveries);
addEndpoint(create_fileattachments_api_attachments_v1);
addEndpoint(update_fileattachments_api_attachments_v1);
addEndpoint(list_fileattachments_api_attachments_v1);
addEndpoint(delete_fileattachments_api_attachments_v1);
addEndpoint(count_fileattachments_api_attachments_v1);
addEndpoint(validate_fileattachments_api_attachments_v1);
addEndpoint(get_sales_info_api_integration_developer);
addEndpoint(list_ratings_api_integration_developer);
addEndpoint(get_user_info_integration_developer_api_users);
addEndpoint(get_sales_info_apps_integration_partner_api_sales_v1);
addEndpoint(get_sales_info_for_tenant_apps_integration_partner_api_sales_v1);
addEndpoint(get_articles_api_time);
addEndpoint(get_registrations_api_time);
addEndpoint(retrieve_tenants_v4_api_warehouse);
addEndpoint(retrieve_deliveries_v1_warehouse_api_deliveries_v1);
addEndpoint(create_deliveries_v1_warehouse_api_inbounddeliveries);
addEndpoint(retrieve_deliveries_v1_warehouse_api_inbounddeliveries);
addEndpoint(update_deliveries_v1_warehouse_api_inbounddeliveries);
addEndpoint(update_release_deliveries_v1_warehouse_api_inbounddeliveries);
addEndpoint(update_void_deliveries_v1_warehouse_api_inbounddeliveries);
addEndpoint(create_deliveries_v1_warehouse_api_outbounddeliveries);
addEndpoint(retrieve_deliveries_v1_warehouse_api_outbounddeliveries);
addEndpoint(update_deliveries_v1_warehouse_api_outbounddeliveries);
addEndpoint(update_release_deliveries_v1_warehouse_api_outbounddeliveries);
addEndpoint(update_void_deliveries_v1_warehouse_api_outbounddeliveries);
addEndpoint(retrieve_custom_documentdeliveries_warehouse_api_documenttypes_v1);
addEndpoint(documenttypes_v1_custom_documentdeliveries_warehouse_api_documenttypes_v1);
addEndpoint(retrieve_documenttypes_v1_custom_documentdeliveries_warehouse_api_documenttypes_v1);
addEndpoint(retrieve_custom_documentdeliveries_warehouse_api_inbound_v1);
addEndpoint(update_custom_documentdeliveries_warehouse_api_inbound_v1);
addEndpoint(update_release_custom_documentdeliveries_warehouse_api_inbound_v1);
addEndpoint(update_void_custom_documentdeliveries_warehouse_api_inbound_v1);
addEndpoint(retrieve_custom_documentdeliveries_warehouse_api_outbound_v1);
addEndpoint(update_custom_documentdeliveries_warehouse_api_outbound_v1);
addEndpoint(update_release_custom_documentdeliveries_warehouse_api_outbound_v1);
addEndpoint(update_void_custom_documentdeliveries_warehouse_api_outbound_v1);
addEndpoint(retrieve_warehouse_api_incominggoods_v1);
addEndpoint(update_warehouse_api_incominggoods_v1);
addEndpoint(incominggoods_v1_warehouse_api_incominggoods_v1);
addEndpoint(retrieve_incominggoods_v1_warehouse_api_incominggoods_v1);
addEndpoint(update_completed_warehouse_api_incominggoods_v1);
addEndpoint(update_release_warehouse_api_incominggoods_v1);
addEndpoint(update_void_warehouse_api_incominggoods_v1);
addEndpoint(retrieve_warehouse_api_productionorders_v1);
addEndpoint(update_warehouse_api_productionorders_v1);
addEndpoint(productionorders_v1_warehouse_api_productionorders_v1);
addEndpoint(retrieve_productionorders_v1_warehouse_api_productionorders_v1);
addEndpoint(retrieve_warehouse_api_purchaseorders_v1);
addEndpoint(update_warehouse_api_purchaseorders_v1);
addEndpoint(purchaseorders_v1_warehouse_api_purchaseorders_v1);
addEndpoint(retrieve_csv_warehouse_api_purchaseorders_v1);
addEndpoint(retrieve_matches_warehouse_api_purchaseorders_v1);
addEndpoint(retrieve_notes_warehouse_api_purchaseorders_v1);
addEndpoint(retrieve_purchaseorders_v1_warehouse_api_purchaseorders_v1);
addEndpoint(send_warehouse_api_purchaseorders_v1);
addEndpoint(sendpurchaseorders_warehouse_api_purchaseorders_v1);
addEndpoint(update_complete_warehouse_api_purchaseorders_v1);
addEndpoint(update_dropshipcomplete_warehouse_api_purchaseorders_v1);
addEndpoint(update_partial_warehouse_api_purchaseorders_v1);
addEndpoint(update_void_warehouse_api_purchaseorders_v1);
addEndpoint(create_purchaseorders_v1_warehouse_api_response);
addEndpoint(retrieve_stockbalance_warehouse_api_status_v1);
addEndpoint(retrieve_warehouse_api_stockpoints_v1);
addEndpoint(update_warehouse_api_stockpoints_v1);
addEndpoint(delete_warehouse_api_stockpoints_v1);
addEndpoint(retrieve_multi_warehouse_api_stockpoints_v1);
addEndpoint(retrieve_stocklocations_warehouse_api_stockpoints_v1);
addEndpoint(retrieve_stockpoints_v1_warehouse_api_stockpoints_v1);
addEndpoint(stockpoints_v1_warehouse_api_stockpoints_v1);
addEndpoint(retrieve_warehouse_api_stocktaking_v1);
addEndpoint(update_warehouse_api_stocktaking_v1);
addEndpoint(delete_warehouse_api_stocktaking_v1);
addEndpoint(addrows_warehouse_api_stocktaking_v1);
addEndpoint(retrieve_candidates_warehouse_api_stocktaking_v1);
addEndpoint(retrieve_stocktaking_v1_warehouse_api_stocktaking_v1);
addEndpoint(stocktaking_v1_warehouse_api_stocktaking_v1);
addEndpoint(update_release_warehouse_api_stocktaking_v1);
addEndpoint(update_void_warehouse_api_stocktaking_v1);
addEndpoint(create_stocktaking_v1_warehouse_api_rows);
addEndpoint(list_stocktaking_v1_warehouse_api_rows);
addEndpoint(delete_stocktaking_v1_warehouse_api_rows);
addEndpoint(delete_all_stocktaking_v1_warehouse_api_rows);
addEndpoint(retrieve_warehouse_api_stocktransfer_v1);
addEndpoint(update_warehouse_api_stocktransfer_v1);
addEndpoint(stocktransfer_v1_warehouse_api_stocktransfer_v1);
addEndpoint(update_release_warehouse_api_stocktransfer_v1);
addEndpoint(update_void_warehouse_api_stocktransfer_v1);

export type Filter = {
  type: 'resource' | 'operation' | 'tag' | 'tool';
  op: 'include' | 'exclude';
  value: string;
};

export function query(filters: Filter[], endpoints: Endpoint[]): Endpoint[] {
  const allExcludes = filters.length > 0 && filters.every((filter) => filter.op === 'exclude');
  const unmatchedFilters = new Set(filters);

  const filtered = endpoints.filter((endpoint: Endpoint) => {
    let included = false || allExcludes;

    for (const filter of filters) {
      if (match(filter, endpoint)) {
        unmatchedFilters.delete(filter);
        included = filter.op === 'include';
      }
    }

    return included;
  });

  // Check if any filters didn't match
  const unmatched = Array.from(unmatchedFilters).filter((f) => f.type === 'tool' || f.type === 'resource');
  if (unmatched.length > 0) {
    throw new Error(
      `The following filters did not match any endpoints: ${unmatched
        .map((f) => `${f.type}=${f.value}`)
        .join(', ')}`,
    );
  }

  return filtered;
}

function match({ type, value }: Filter, endpoint: Endpoint): boolean {
  switch (type) {
    case 'resource': {
      const regexStr = '^' + normalizeResource(value).replace(/\*/g, '.*') + '$';
      const regex = new RegExp(regexStr);
      return regex.test(normalizeResource(endpoint.metadata.resource));
    }
    case 'operation':
      return endpoint.metadata.operation === value;
    case 'tag':
      return endpoint.metadata.tags.includes(value);
    case 'tool':
      return endpoint.tool.name === value;
  }
}

function normalizeResource(resource: string): string {
  return resource.toLowerCase().replace(/[^a-z.*\-_]*/g, '');
}
